import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  resolve: {
    alias: {
      '#layers/thei': fileURLToPath(new URL('.', import.meta.url)),
      // Generated by the Nuxt module at build time; tests get a stand-in.
      '#thei/static-public': fileURLToPath(
        new URL('./tests/helpers/static-public.ts', import.meta.url),
      ),
    },
  },
  test: {
    exclude: [
      '**/node_modules/**',
      '**/.nuxt/**',
      '**/.output/**',
      'tests/e2e/**',
    ],
    environment: 'node',
  },
});
