import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitest/config';

const testExclude = [
  '**/node_modules/**',
  '**/.nuxt/**',
  '**/.output/**',
  'tests/e2e/**',
  // The release bench runs in Docker, and may keep a clone of this repository
  // in its artifacts.
  'tests/release/**',
];

export default defineConfig({
  resolve: {
    alias: {
      '#layers/thei': fileURLToPath(new URL('.', import.meta.url)),
      // Generated by the Nuxt module at build time; tests get a stand-in.
      '#thei/static-public': fileURLToPath(
        new URL('./tests/helpers/static-public.ts', import.meta.url),
      ),
      '#thei/icon-symbols': fileURLToPath(
        new URL('./tests/helpers/icon-symbols.ts', import.meta.url),
      ),
      '#thei/og-signature': fileURLToPath(
        new URL('./tests/helpers/og-signature.ts', import.meta.url),
      ),
    },
  },
  test: {
    exclude: testExclude,
    typecheck: { exclude: testExclude },
    environment: 'node',
  },
});
