// Generated by `bun run db:baseline`. Do not edit by hand.
import { defineMigration } from './types';

export const baselineSql: string[] = [
  `CREATE TABLE \`profiles\` (
	\`profileId\` text PRIMARY KEY NOT NULL,
	\`displayName\` text NOT NULL,
	\`slogan\` text DEFAULT '' NOT NULL,
	\`nickname\` text DEFAULT '' NOT NULL,
	\`birthDate\` text DEFAULT '' NOT NULL,
	\`currentAvatarId\` text,
	\`bannerAssetUuid\` text,
	\`faviconAssetUuid\` text,
	\`facts\` text DEFAULT '[]' NOT NULL
);
`,
  `CREATE TABLE \`profile-avatars\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`assetUuid\` text NOT NULL,
	\`createdAt\` integer NOT NULL
);
`,
  `CREATE INDEX \`profile-avatars-date-idx\` ON \`profile-avatars\` (\`createdAt\`,\`id\`);`,
  `CREATE TABLE \`profile-statuses\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`kind\` text DEFAULT 'regular' NOT NULL,
	\`assetUuid\` text,
	\`text\` text NOT NULL,
	\`createdAt\` integer NOT NULL
);
`,
  `CREATE INDEX \`profile-statuses-date-idx\` ON \`profile-statuses\` (\`createdAt\`,\`id\`);`,
  `CREATE TABLE \`profile-pinned-pages\` (
	\`pageUuid\` text PRIMARY KEY NOT NULL,
	\`sortOrder\` integer NOT NULL,
	FOREIGN KEY (\`pageUuid\`) REFERENCES \`pages\`(\`pageUuid\`) ON UPDATE no action ON DELETE cascade
);
`,
  `CREATE TABLE \`profile-external-links\` (
	\`url\` text PRIMARY KEY NOT NULL,
	\`name\` text NOT NULL,
	\`isPrivate\` integer DEFAULT false NOT NULL,
	\`sortOrder\` integer NOT NULL
);
`,
  `CREATE TABLE \`assets\` (
	\`assetUuid\` text PRIMARY KEY NOT NULL,
	\`slug\` text NOT NULL,
	\`extension\` text NOT NULL,
	\`familyUuid\` text NOT NULL,
	\`contentHash\` text NOT NULL,
	\`settingsKey\` text NOT NULL,
	\`settings\` text,
	\`type\` text NOT NULL,
	\`size\` integer NOT NULL,
	\`touchedAt\` integer NOT NULL,
	\`meta\` text
);
`,
  `CREATE UNIQUE INDEX \`assets_slug_unique\` ON \`assets\` (\`slug\`);`,
  `CREATE UNIQUE INDEX \`assets_family_content_settings_idx\` ON \`assets\` (\`familyUuid\`,\`contentHash\`,\`settingsKey\`);`,
  `CREATE INDEX \`assets_family_idx\` ON \`assets\` (\`familyUuid\`);`,
  `CREATE INDEX \`assets_content_hash_idx\` ON \`assets\` (\`contentHash\`);`,
  `CREATE TABLE \`asset-usages\` (
	\`assetUuid\` text NOT NULL,
	\`containerType\` text NOT NULL,
	\`containerId\` text NOT NULL,
	\`role\` text NOT NULL,
	\`meta\` text,
	PRIMARY KEY(\`assetUuid\`, \`containerType\`, \`containerId\`, \`role\`)
);
`,
  `CREATE INDEX \`asset-usages-container-idx\` ON \`asset-usages\` (\`containerType\`,\`containerId\`);`,
  `CREATE INDEX \`asset-usages-asset-idx\` ON \`asset-usages\` (\`assetUuid\`);`,
  `CREATE TABLE \`backups\` (
	\`backupUuid\` text PRIMARY KEY NOT NULL,
	\`kind\` text NOT NULL,
	\`startedAt\` integer NOT NULL,
	\`completedAt\` integer NOT NULL,
	\`fileCount\` integer NOT NULL,
	\`byteCount\` integer NOT NULL,
	\`clientLabel\` text
);
`,
  `CREATE INDEX \`backups-completed-idx\` ON \`backups\` (\`completedAt\`);`,
  `CREATE TABLE \`content\` (
	\`contentUuid\` text PRIMARY KEY NOT NULL,
	\`ownerType\` text NOT NULL,
	\`ownerId\` text NOT NULL,
	\`slot\` text NOT NULL,
	\`data\` text NOT NULL,
	\`blockCount\` integer DEFAULT 0 NOT NULL,
	\`assetCount\` integer DEFAULT 0 NOT NULL,
	\`assetTotalSize\` integer DEFAULT 0 NOT NULL,
	\`createdAt\` integer NOT NULL,
	\`updatedAt\` integer NOT NULL
);
`,
  `CREATE UNIQUE INDEX \`content-owner-slot-idx\` ON \`content\` (\`ownerType\`,\`ownerId\`,\`slot\`);`,
  `CREATE INDEX \`content-owner-idx\` ON \`content\` (\`ownerType\`,\`ownerId\`);`,
  `CREATE TABLE \`events\` (
	\`eventUuid\` text PRIMARY KEY NOT NULL,
	\`title\` text NOT NULL,
	\`summary\` text NOT NULL,
	\`access\` text NOT NULL,
	\`humanReadableSlug\` text NOT NULL,
	\`publicId\` text NOT NULL,
	\`action\` text,
	\`reminder\` text DEFAULT '' NOT NULL,
	\`createdAt\` integer NOT NULL,
	\`updatedAt\` integer NOT NULL
);
`,
  `CREATE UNIQUE INDEX \`events_publicId_unique\` ON \`events\` (\`publicId\`);`,
  `CREATE TABLE \`projects\` (
	\`projectUuid\` text PRIMARY KEY NOT NULL,
	\`title\` text NOT NULL,
	\`summary\` text NOT NULL,
	\`access\` text NOT NULL,
	\`humanReadableSlug\` text NOT NULL,
	\`publicId\` text NOT NULL,
	\`showcase\` integer DEFAULT false NOT NULL,
	\`cv\` integer DEFAULT false NOT NULL,
	\`action\` text,
	\`reminder\` text DEFAULT '' NOT NULL,
	\`createdAt\` integer NOT NULL,
	\`updatedAt\` integer NOT NULL
);
`,
  `CREATE UNIQUE INDEX \`projects_publicId_unique\` ON \`projects\` (\`publicId\`);`,
  `CREATE TABLE \`pages\` (
	\`pageUuid\` text PRIMARY KEY NOT NULL,
	\`slug\` text NOT NULL,
	\`title\` text NOT NULL,
	\`summary\` text NOT NULL,
	\`access\` text NOT NULL,
	\`reminder\` text DEFAULT '' NOT NULL,
	\`createdAt\` integer NOT NULL,
	\`updatedAt\` integer NOT NULL
);
`,
  `CREATE UNIQUE INDEX \`pages_slug_unique\` ON \`pages\` (\`slug\`);`,
  `CREATE TABLE \`admin-sessions\` (
	\`sessionUuid\` text PRIMARY KEY NOT NULL,
	\`data\` text NOT NULL
);
`,
  `CREATE TABLE \`sign-in-links\` (
	\`tokenHash\` text PRIMARY KEY NOT NULL,
	\`createdAt\` integer NOT NULL,
	\`expiresAt\` integer NOT NULL,
	\`createdFrom\` text
);
`,
  `CREATE INDEX \`sign-in-links-expires-idx\` ON \`sign-in-links\` (\`expiresAt\`);`,
  `CREATE TABLE \`share-links\` (
	\`shareUuid\` text PRIMARY KEY NOT NULL,
	\`tokenHash\` text NOT NULL,
	\`entityType\` text NOT NULL,
	\`entityUuid\` text NOT NULL,
	\`createdAt\` integer NOT NULL,
	\`expiresAt\` integer NOT NULL
);
`,
  `CREATE UNIQUE INDEX \`share-links_tokenHash_unique\` ON \`share-links\` (\`tokenHash\`);`,
  `CREATE INDEX \`share-links-entity-idx\` ON \`share-links\` (\`entityType\`,\`entityUuid\`);`,
  `CREATE INDEX \`share-links-expires-idx\` ON \`share-links\` (\`expiresAt\`);`,
  `CREATE TABLE \`project-content-sections\` (
	\`sectionUuid\` text PRIMARY KEY NOT NULL,
	\`projectUuid\` text NOT NULL,
	\`title\` text NOT NULL,
	\`summary\` text DEFAULT '' NOT NULL,
	\`humanReadableSlug\` text NOT NULL,
	\`publicId\` text NOT NULL,
	\`isPrivate\` integer DEFAULT false NOT NULL,
	\`sortOrder\` integer NOT NULL,
	\`createdAt\` integer NOT NULL,
	\`updatedAt\` integer NOT NULL
);
`,
  `CREATE INDEX \`project-content-sections-project-idx\` ON \`project-content-sections\` (\`projectUuid\`,\`sortOrder\`);`,
  `CREATE UNIQUE INDEX \`project-content-sections-public-id-unique\` ON \`project-content-sections\` (\`publicId\`);`,
  `CREATE TABLE \`project-stages\` (
	\`stageUuid\` text PRIMARY KEY NOT NULL,
	\`projectUuid\` text NOT NULL,
	\`title\` text NOT NULL,
	\`summary\` text DEFAULT '' NOT NULL,
	\`humanReadableSlug\` text NOT NULL,
	\`publicId\` text NOT NULL,
	\`isPrivate\` integer DEFAULT false NOT NULL,
	\`createdAt\` integer NOT NULL,
	\`updatedAt\` integer NOT NULL
);
`,
  `CREATE INDEX \`project-stages-project-idx\` ON \`project-stages\` (\`projectUuid\`);`,
  `CREATE UNIQUE INDEX \`project-stages-public-id-unique\` ON \`project-stages\` (\`publicId\`);`,
  `CREATE TABLE \`stage-periods\` (
	\`stageType\` text NOT NULL,
	\`stageUuid\` text NOT NULL,
	\`sortOrder\` integer NOT NULL,
	\`startDate\` text NOT NULL,
	\`endDate\` text NOT NULL,
	\`precision\` text DEFAULT 'exact' NOT NULL,
	\`precisionNote\` text DEFAULT '' NOT NULL,
	PRIMARY KEY(\`stageType\`, \`stageUuid\`, \`sortOrder\`),
	CONSTRAINT "stage-periods-stage-type-check" CHECK("stage-periods"."stageType" in ('project-stage', 'event-stage'))
);
`,
  `CREATE TABLE \`project-relations\` (
	\`firstProjectUuid\` text NOT NULL,
	\`secondProjectUuid\` text NOT NULL,
	\`type\` text NOT NULL,
	\`note\` text,
	\`firstSortOrder\` integer NOT NULL,
	\`secondSortOrder\` integer NOT NULL,
	PRIMARY KEY(\`firstProjectUuid\`, \`secondProjectUuid\`),
	FOREIGN KEY (\`firstProjectUuid\`) REFERENCES \`projects\`(\`projectUuid\`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (\`secondProjectUuid\`) REFERENCES \`projects\`(\`projectUuid\`) ON UPDATE no action ON DELETE cascade
);
`,
  `CREATE INDEX \`project-relations-first-idx\` ON \`project-relations\` (\`firstProjectUuid\`,\`firstSortOrder\`);`,
  `CREATE INDEX \`project-relations-second-idx\` ON \`project-relations\` (\`secondProjectUuid\`,\`secondSortOrder\`);`,
  `CREATE TABLE \`tags\` (
	\`tagUuid\` text PRIMARY KEY NOT NULL,
	\`title\` text NOT NULL,
	\`normalizedTitle\` text NOT NULL,
	\`slug\` text NOT NULL,
	\`publicId\` text NOT NULL,
	\`description\` text DEFAULT '' NOT NULL,
	\`accentColor\` text
);
`,
  `CREATE UNIQUE INDEX \`tags_normalizedTitle_unique\` ON \`tags\` (\`normalizedTitle\`);`,
  `CREATE UNIQUE INDEX \`tags_slug_unique\` ON \`tags\` (\`slug\`);`,
  `CREATE UNIQUE INDEX \`tags_publicId_unique\` ON \`tags\` (\`publicId\`);`,
  `CREATE TABLE \`tag-usages\` (
	\`tagUuid\` text NOT NULL,
	\`containerType\` text NOT NULL,
	\`containerId\` text NOT NULL,
	\`sortOrder\` integer NOT NULL,
	PRIMARY KEY(\`tagUuid\`, \`containerType\`, \`containerId\`)
);
`,
  `CREATE INDEX \`tag-usages-container-idx\` ON \`tag-usages\` (\`containerType\`,\`containerId\`);`,
  `CREATE INDEX \`tag-usages-tag-idx\` ON \`tag-usages\` (\`tagUuid\`);`,
  `CREATE TABLE \`external-links\` (
	\`url\` text PRIMARY KEY NOT NULL,
	\`title\` text,
	\`description\` text,
	\`faviconKey\` text NOT NULL,
	\`accent\` text,
	\`touchedAt\` integer NOT NULL
);
`,
  `CREATE TABLE \`project-external-links\` (
	\`projectUuid\` text NOT NULL,
	\`url\` text NOT NULL,
	\`name\` text NOT NULL,
	\`sortOrder\` integer NOT NULL,
	\`isPrivate\` integer DEFAULT false NOT NULL,
	PRIMARY KEY(\`projectUuid\`, \`url\`),
	FOREIGN KEY (\`projectUuid\`) REFERENCES \`projects\`(\`projectUuid\`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (\`url\`) REFERENCES \`external-links\`(\`url\`) ON UPDATE no action ON DELETE no action
);
`,
  `CREATE INDEX \`project-external-links-project-idx\` ON \`project-external-links\` (\`projectUuid\`,\`sortOrder\`);`,
  `CREATE TABLE \`event-external-links\` (
	\`eventUuid\` text NOT NULL,
	\`url\` text NOT NULL,
	\`name\` text NOT NULL,
	\`sortOrder\` integer NOT NULL,
	\`isPrivate\` integer DEFAULT false NOT NULL,
	PRIMARY KEY(\`eventUuid\`, \`url\`),
	FOREIGN KEY (\`eventUuid\`) REFERENCES \`events\`(\`eventUuid\`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (\`url\`) REFERENCES \`external-links\`(\`url\`) ON UPDATE no action ON DELETE no action
);
`,
  `CREATE INDEX \`event-external-links-event-idx\` ON \`event-external-links\` (\`eventUuid\`,\`sortOrder\`);`,
  `CREATE TABLE \`event-project-relations\` (
	\`eventUuid\` text NOT NULL,
	\`projectUuid\` text NOT NULL,
	\`note\` text,
	\`sortOrder\` integer NOT NULL,
	PRIMARY KEY(\`eventUuid\`, \`projectUuid\`),
	FOREIGN KEY (\`eventUuid\`) REFERENCES \`events\`(\`eventUuid\`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (\`projectUuid\`) REFERENCES \`projects\`(\`projectUuid\`) ON UPDATE no action ON DELETE cascade
);
`,
  `CREATE INDEX \`event-project-relations-event-idx\` ON \`event-project-relations\` (\`eventUuid\`,\`sortOrder\`);`,
  `CREATE INDEX \`event-project-relations-project-idx\` ON \`event-project-relations\` (\`projectUuid\`);`,
];

export default defineMigration({
  id: '0.0.1/001-baseline',
  version: '0.0.1',
  title: 'Create the initial Thei schema',
  up({ rawDb }) {
    for (const statement of baselineSql) rawDb.prepare(statement).run();
  },
});
