/**
 * Regenerates `update/migrations/0.0.1-baseline.ts` from the current Drizzle
 * schema. Development only — run it with `bun run db:baseline` whenever the
 * baseline needs to be re-cut, and commit the result.
 *
 * The baseline is the schema every instance starts from. Once a release has
 * shipped, its statements must not change: schema changes after that point
 * belong in a new migration file. `tests/server/migrations-baseline.test.ts`
 * guards the two against drifting apart.
 */
import { writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  generateSQLiteDrizzleJson,
  generateSQLiteMigration,
} from 'drizzle-kit/api';
import { schema } from '../../server/thei/db/schema/index.ts';

const currentDir = dirname(fileURLToPath(import.meta.url));
const target = join(currentDir, '../migrations/0.0.1-baseline.ts');

const statements = await generateSQLiteMigration(
  await generateSQLiteDrizzleJson({}),
  await generateSQLiteDrizzleJson(schema),
);

const body = statements
  .map((statement) => `  \`${statement.replace(/`/g, '\\`')}\`,`)
  .join('\n');

const contents = `// Generated by \`bun run db:baseline\`. Do not edit by hand.
import { defineMigration } from './types';

export const baselineSql: string[] = [
${body}
];

export default defineMigration({
  id: '0.0.1/001-baseline',
  version: '0.0.1',
  title: 'Create the initial Thei schema',
  up({ rawDb }) {
    for (const statement of baselineSql) rawDb.prepare(statement).run();
  },
});
`;

await writeFile(target, contents, 'utf-8');

console.log(`Wrote ${statements.length} baseline statements to ${target}`);
